config/routes.rb
Rails.application.routes.draw do
  resources :mains
  root 'mains#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main.rb
class Main < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: %i[ show edit update destroy ]

  # GET /mains or /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains or /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: "Main was successfully created." }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1 or /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to @main, notice: "Main was successfully updated." }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1 or /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: "Main was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_params
      params.fetch(:main, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAutoReload</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mains/_form.html.erb
<%= form_with(model: main) do |form| %>
  <% if main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
        <% main.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<h1>Editing Main</h1>

<%= render 'form', main: @main %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mains</h1>

<h1>We are all here for testing</h1>
<h1>Let's see if we get to be auto reloaded :p</h1>
<h1>I am the new line</h1>


<h1>I am the new line i show up from live reload</h1>

app/views/mains/new.html.erb
<h1>New Main</h1>




<%= render 'form', main: @main %>

<%= link_to 'Back', mains_path %>

app/views/mains/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_main_path(@main) %> |
<%= link_to 'Back', mains_path %>